apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: __YOUR_DATA__/mystandard
  newTag: 1.1.3.NOSSL


configMapGenerator:
- files:
  - config/application.yml
  - config/application-detail.yml
  - config/application-env.yml
  - config/default_state_machine.xml
  - config/index_definition.json
  - config/mybox.properties
  name: mystandard-config
- files:
  - init/fuseki-docker/configuration/mystd.ttl
  name: fuseki-config

namespace: k910p

patches:
- path: endpoints/logstash-endpoints.yaml
  target:
    kind: Endpoints
    name: k930-logstash
- path: envvars/proxy-settings.yaml
  target:
    kind: Deployment
    name: mystandard-deployment
- path: envvars/mystandard-init-envvars.yaml
  target:
    kind: Deployment
    name: mystandard-deployment
- path: args/mystandard-init-args.yaml
  target:
    kind: Deployment
    name: mystandard-deployment

- path: envvars/sync-config-from-git-env.yaml
  target:
    kind: Job
    name: sync-config-from-git


patchesJson6902:
- path: ingress/ingress-mystandard.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: mystandard-ingress
    version: v1
