apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: mystandard-container
          env:
            - name: http_proxy
              value:  "__YOUR_DATA__"
            - name: https_proxy
              value:  "__YOUR_DATA__"
            - name: no_proxy
              value: "127.0.0.1,__YOUR_DATA__"
            - name: MYPLACE_VM_JAVA_OPTS
              value: "-Dhttp.proxyHost=__YOUR_DATA__ -Dhttp.proxyPort=8000 -Dhttp.nonProxyHosts='127.0.0.1|__YOUR_DATA__' -Dhttps.proxyHost=__YOUR_DATA__ -Dhttps.proxyPort=__YOUR_DATA__"
            - name: MYPROFILE
              value: "__YOUR_DATA__"

