apiVersion: v1
kind: Service
metadata:
  name: mystandard
spec:
  ports:
  - name: mystandard-port
    port: __YOUR_DATA__
    targetPort: __YOUR_DATA__
  selector:
    templateName: mystandard-template
  type: ClusterIP
